remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Mon Site Personnel
description: Bienvenue sur mon site personnel où je partage mes projets et idées
show_downloads: false
google_analytics:
